name: Flutter action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: ['v1.13.5']
    steps:
      - uses: actions/checkout@v1
      - uses: takuyaohashi/setup-flutter@v1
        with:
          flutter-version: ${{ matrix.flutter }}
          channel: 'stable'
      - name: test
        run: flutter test
